version: "3.2"
services:
  sql-server-db:
    build:
      context: .
      dockerfile: sql/Dockerfile
    container_name: sql-server-db
    image: mcmoe/mssqldocker:v2017.CU24.0
    ports:
      - "1400:1433"
    environment:
      SA_PASSWORD: "kursPswd123"
      MSSQL_DB: TEST
      MSSQL_USER: kursUser
      MSSQL_PASSWORD: kursPswd
      ACCEPT_EULA: "Y"
